"""add unique constraints to stock_prices and news_articles

Revision ID: 501cb93a9dff
Revises: 93b8e2732813
Create Date: 2026-03-29 20:12:08.628910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501cb93a9dff'
down_revision: Union[str, Sequence[str], None] = '93b8e2732813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_news_ticker_date_url', 'news_articles', ['ticker', 'published_date', 'article_url'])
    op.create_unique_constraint('uq_stock_ticker_date', 'stock_prices', ['ticker', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices', sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('uq_stock_ticker_date', 'stock_prices', type_='unique')
    op.drop_constraint('uq_news_ticker_date_url', 'news_articles', type_='unique')
    # ### end Alembic commands ###
