"""add news_articles table

Revision ID: 93b8e2732813
Revises: cd4606f6b33c
Create Date: 2026-03-17 22:23:16.557013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '93b8e2732813'
down_revision: Union[str, Sequence[str], None] = 'cd4606f6b33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('article_url', sa.String(), nullable=False),
    sa.Column('news_source', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('index_within_chunk', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_articles')
    # ### end Alembic commands ###
